server:
  port: 80
  servlet:
    context-path: /guteam
    session:
      timeout: 60m
  connection-timeout: 30s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  rabbitmq:
    host: 192.168.100.40
    username: root
    password: 123456
    port: 5672
  security:
    user:
      name: user
      password: 123
  application:
    name: isspers
  redis:
    hostName: 192.168.100.20
    port: 6379
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    password:
    timeout: 1000ms
    #    sentinel:
    #      master: mymaster
    #      nodes: 192.168.100.20:26379, 192.168.100.20:26380, 192.168.100.20:26381
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 1ms
  redis2:
    hostName: 192.168.100.20
    port: 6379
    database: 10
    password:
    timeout: 1000ms
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: -1
        max-wait: 1ms
  redis3:
    hostName: 192.168.100.20
    port: 6379
    database: 11
    password:
    timeout: 1000ms
    lettuce:
      pool:
        max-idle: 10
        min-idle: 0
        max-active: -1
        max-wait: 1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.10:3306/isspers?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: file:${isspersPath},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
  data:
    mongodb:
      uri: mongodb://root:123456@192.168.100.30:27017/mlp
      authentication-database: admin

logging:
  path: E:\resource\isspers\log
  level:
    com:
      guteam: info
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n
#    file: %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n

#配置指定类或命名空间的日志级别，SpringBoot默认info级别
#logging.level.cn.coreqi = trace



isspersPath: E:/resource/isspers/
systemImage: system/image/
systemFile: system/file/
userImage: user/image/
dataPath: file/data/
algorithmPath: algorithm/
navigationRedisTime: 1800
displayRedisTime: 1800
outputRedisTime: 1800
inputRedisTime: 1800
systemInfoRedisTime: 1800
algorithmBaseRedisTime: 1800
#dataPath: E:/resource/isspers/data/

#algorithmPath: E:/resource/isspers/algorithm/
#imagePath: E:/resource/isspers/image/


